steps:
# api
- name: 'microsoft/dotnet:2.0-sdk'
  entrypoint: dotnet
  args: ['publish', '-c', 'Release', '-o', './dist']
  dir: 'WebApplication'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/cabinet-api-_BRANCH', '.']
  dir: 'WebApplication'
# core
- name: 'microsoft/dotnet:2.0-sdk'
  entrypoint: dotnet
  args: ['publish', '-c', 'Release', '-o', './dist']
  dir: 'QueueService'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/cabinet-core-_BRANCH', '.']
  dir: 'QueueService'
images: ['eu.gcr.io/$PROJECT_ID/cabinet-api-_BRANCH', 'eu.gcr.io/$PROJECT_ID/cabinet-core-_BRANCH']