// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/eth2gold/event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Eth2Gold.Event {

  /// <summary>Holder for reflection information generated from proto/eth2gold/event.proto</summary>
  public static partial class EventReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/eth2gold/event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpwcm90by9ldGgyZ29sZC9ldmVudC5wcm90bxIFZXZlbnQiXAoOT3JkZXJE",
            "ZXBvc2l0ZWQSEgoKRXh0ZXJuYWxJRBgBIAEoBBIRCglFdGhBbW91bnQYAiAB",
            "KAkSDgoGU2VuZGVyGAMgASgJEhMKC1RyYW5zYWN0aW9uGAQgASgJIhMKEU9y",
            "ZGVyRGVwb3NpdGVkQWNrQhdaBG5hdHOqAg5FdGgyR29sZC5FdmVudGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Eth2Gold.Event.OrderDeposited), global::Eth2Gold.Event.OrderDeposited.Parser, new[]{ "ExternalID", "EthAmount", "Sender", "Transaction" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Eth2Gold.Event.OrderDepositedAck), global::Eth2Gold.Event.OrderDepositedAck.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// OrderDeposited notifies about completed ETH deposit
  /// </summary>
  public sealed partial class OrderDeposited : pb::IMessage<OrderDeposited> {
    private static readonly pb::MessageParser<OrderDeposited> _parser = new pb::MessageParser<OrderDeposited>(() => new OrderDeposited());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderDeposited> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eth2Gold.Event.EventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDeposited() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDeposited(OrderDeposited other) : this() {
      externalID_ = other.externalID_;
      ethAmount_ = other.ethAmount_;
      sender_ = other.sender_;
      transaction_ = other.transaction_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDeposited Clone() {
      return new OrderDeposited(this);
    }

    /// <summary>Field number for the "ExternalID" field.</summary>
    public const int ExternalIDFieldNumber = 1;
    private ulong externalID_;
    /// <summary>
    /// External order ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ExternalID {
      get { return externalID_; }
      set {
        externalID_ = value;
      }
    }

    /// <summary>Field number for the "EthAmount" field.</summary>
    public const int EthAmountFieldNumber = 2;
    private string ethAmount_ = "";
    /// <summary>
    /// ETH amount deposited
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EthAmount {
      get { return ethAmount_; }
      set {
        ethAmount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sender" field.</summary>
    public const int SenderFieldNumber = 3;
    private string sender_ = "";
    /// <summary>
    /// Sender Ethereum address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sender {
      get { return sender_; }
      set {
        sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Transaction" field.</summary>
    public const int TransactionFieldNumber = 4;
    private string transaction_ = "";
    /// <summary>
    /// Ethereum transaction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Transaction {
      get { return transaction_; }
      set {
        transaction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderDeposited);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderDeposited other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExternalID != other.ExternalID) return false;
      if (EthAmount != other.EthAmount) return false;
      if (Sender != other.Sender) return false;
      if (Transaction != other.Transaction) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ExternalID != 0UL) hash ^= ExternalID.GetHashCode();
      if (EthAmount.Length != 0) hash ^= EthAmount.GetHashCode();
      if (Sender.Length != 0) hash ^= Sender.GetHashCode();
      if (Transaction.Length != 0) hash ^= Transaction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ExternalID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ExternalID);
      }
      if (EthAmount.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EthAmount);
      }
      if (Sender.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Sender);
      }
      if (Transaction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Transaction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ExternalID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ExternalID);
      }
      if (EthAmount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EthAmount);
      }
      if (Sender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
      }
      if (Transaction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Transaction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderDeposited other) {
      if (other == null) {
        return;
      }
      if (other.ExternalID != 0UL) {
        ExternalID = other.ExternalID;
      }
      if (other.EthAmount.Length != 0) {
        EthAmount = other.EthAmount;
      }
      if (other.Sender.Length != 0) {
        Sender = other.Sender;
      }
      if (other.Transaction.Length != 0) {
        Transaction = other.Transaction;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ExternalID = input.ReadUInt64();
            break;
          }
          case 18: {
            EthAmount = input.ReadString();
            break;
          }
          case 26: {
            Sender = input.ReadString();
            break;
          }
          case 34: {
            Transaction = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// OrderDepositedAck is a reply for OrderDeposited
  /// </summary>
  public sealed partial class OrderDepositedAck : pb::IMessage<OrderDepositedAck> {
    private static readonly pb::MessageParser<OrderDepositedAck> _parser = new pb::MessageParser<OrderDepositedAck>(() => new OrderDepositedAck());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderDepositedAck> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Eth2Gold.Event.EventReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDepositedAck() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDepositedAck(OrderDepositedAck other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderDepositedAck Clone() {
      return new OrderDepositedAck(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderDepositedAck);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderDepositedAck other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderDepositedAck other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
