steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'WebApplication/Client'
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: node
  args: ['version.js', '$SHORT_SHA', '$BRANCH_NAME']
  dir: 'WebApplication/Client'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--', '--prod', '--env=${_NGENV}', '--aot', '--build-optimizer=false', '--no-sourcemap']
  dir: 'WebApplication/Client'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/cabinet-client:$BRANCH_NAME', '.']
  dir: 'WebApplication/Client'
images: ['eu.gcr.io/$PROJECT_ID/cabinet-client:$BRANCH_NAME']